docs: adds usage info for reset command
shahednasser/cross-post pull request #25
Opened 2022-03-29 02:55 UTC by HarshaVardhanNakkina

- added usage info for reset command
- added a link in the table of contents too

2022-04-16 12:29 UTC, shahednasser requested changes
Thank you for your work @HarshaVardhanNakkina I've added some comments below

2022-04-16 12:29 UTC, shahednasser commented on README.md
> +```cross-post config reset <platform name>```
You should add a new line after the first 3 backticks and before the last 3 backticks. Also, you should add the language (in this case `bash`) after the first 3 backticks.

Please apply that to all code blocks

2022-04-16 12:29 UTC, shahednasser commented on README.md
> +##### Reset Configuration Values
Change this to `####`

2022-05-03 06:07 UTC, HarshaVardhanNakkina commented
sorry for the delay, I was busy with my work

2022-05-03 06:08 UTC, HarshaVardhanNakkina commented on README.md
> +```cross-post config reset <platform name>```
done

2022-05-03 06:08 UTC, HarshaVardhanNakkina commented on README.md
> +##### Reset Configuration Values
done

2022-06-28 18:59 UTC, merged

2022-06-28 18:59 UTC, shahednasser commented
Thank you @HarshaVardhanNakkina for your work!